// Copyright 2020 Dhiraj Wishal
// SPDX-License-Identifier: Apache-2.0

#pragma once
#ifndef _DYNAMIK_THREAD_COMMAND_H
#define _DYNAMIK_THREAD_COMMAND_H

#include "Core/Macros/Global.h"

/* Thread command types */
enum class DMK_API DMKThreadControlCommand {
	DMK_THREAD_CONTROL_COMMAND_UNDEFINED,
	DMK_THREAD_CONTROL_COMMAND_TERMINATE,
	DMK_THREAD_CONTROL_COMMAND_FORCE_TERMINATE,
	DMK_THREAD_CONTROL_COMMAND_RESET,
	DMK_THREAD_CONTROL_COMMAND_SYNC,
};

#endif // !_DYNAMIK_THREAD_COMMAND_H
