// Copyright 2020 Dhiraj Wishal
// SPDX-License-Identifier: Apache-2.0

#pragma once
#ifndef _DYNAMIK_PIPELINE_TYPE_DEFINES_H
#define _DYNAMIK_PIPELINE_TYPE_DEFINES_H

/*
 Author:	Dhiraj Wishal
 Date:		17/06/2020
*/

namespace Dynamik
{
	/* Renderer Primitive Topology */
	enum class DMK_API RPrimitiveTopology {
		PRIMITIVE_TOPOLOGY_POINT_LIST,
		PRIMITIVE_TOPOLOGY_LINE_LIST,
		PRIMITIVE_TOPOLOGY_LINE_STRIP,
		PRIMITIVE_TOPOLOGY_TRIANGLE_LIST,
		PRIMITIVE_TOPOLOGY_TRIANGLE_STRIP,
		PRIMITIVE_TOPOLOGY_TRIANGLE_FAN,
		PRIMITIVE_TOPOLOGY_LINE_LIST_WITH_ADJACENCY,
		PRIMITIVE_TOPOLOGY_LINE_STRIP_WITH_ADJACENCY,
		PRIMITIVE_TOPOLOGY_TRIANGLE_LIST_WITH_ADJACENCY,
		PRIMITIVE_TOPOLOGY_TRIANGLE_STRIP_WITH_ADJACENCY,
		PRIMITIVE_TOPOLOGY_PATCH_LIST,
	};

	/* Renderer Polygon Mode */
	enum class DMK_API RPolygonMode {
		POLYGON_MODE_FILL,
		POLYGON_MODE_LINE,
		POLYGON_MODE_POINT,
		POLYGON_MODE_FILL_RECTANGLE,
	};

	/* Renderer Cull Mode */
	enum class DMK_API RCullMode {
		CULL_MODE_NONE = 0,
		CULL_MODE_FRONT_BIT = BIT_SHIFT(1),
		CULL_MODE_BACK_BIT = BIT_SHIFT(2),
		CULL_MODE_FRONT_AND_BACK_BIT = BIT_SHIFT(3),
	};

	/* Renderer Front Face */
	enum class DMK_API RFrontFace {
		FRONT_FACE_COUNTER_CLOCKWISE,
		FRONT_FACE_CLOCKWISE,
	};

	/* Renderer Logic Op */
	enum class DMK_API RLogicOp {
		LOGIC_OP_CLEAR,
		LOGIC_OP_AND,
		LOGIC_OP_AND_REVERSE,
		LOGIC_OP_COPY,
		LOGIC_OP_AND_INVERTED,
		LOGIC_OP_NO_OP,
		LOGIC_OP_XOR,
		LOGIC_OP_OR,
		LOGIC_OP_NOR,
		LOGIC_OP_EQUIVALENT,
		LOGIC_OP_INVERT,
		LOGIC_OP_OR_REVERSE,
		LOGIC_OP_COPY_INVERTED,
		LOGIC_OP_OR_INVERTED,
		LOGIC_OP_NAND,
		LOGIC_OP_SET,
	};

	/* Renderer Dynamic State */
	enum class DMK_API RDynamicState {
		DYNAMIC_STATE_VIEWPORT,
		DYNAMIC_STATE_SCISSOR,
		DYNAMIC_STATE_LINE_WIDTH,
		DYNAMIC_STATE_DEPTH_BIAS,
		DYNAMIC_STATE_BLEND_CONSTANTS,
		DYNAMIC_STATE_DEPTH_BOUNDS,
		DYNAMIC_STATE_STENCIL_COMPARE_MASK,
		DYNAMIC_STATE_STENCIL_WRITE_MASK,
		DYNAMIC_STATE_STENCIL_REFERENCE,
		DYNAMIC_STATE_VIEWPORT_W_SCALING,
		DYNAMIC_STATE_DISCARD_RECTANGLE_EXT,
		DYNAMIC_STATE_SAMPLE_LOCATIONS_EXT,
		DYNAMIC_STATE_VIEWPORT_SHADING_RATE_PALETTE,
		DYNAMIC_STATE_VIEWPORT_COARSE_SAMPLE_ORDER,
		DYNAMIC_STATE_EXCLUSIVE_SCISSOR,
		DYNAMIC_STATE_LINE_STIPPLE_EXT,
	};
}

#endif // !_DYNAMIK_PIPELINE_TYPE_DEFINES_H
